### ISSUE TITLE
NAs not treated well in the etna update_from_csv path

### ISSUE THREAD

**Issue by dtm2451** [mountetna/monoetna#1138]
In trying to load data into the xneo1 diagnostics model from a csv, I hit an error that 'NA' is invalid syntax for type boolean.  I also notice that NAs in integer and float fields are getting turned into 0s before the stack trace, instead of staying as empty fields.

Call / stack trace:
```
etna administrate models attributes update_from_csv xneo1 diagnostics CoProject_limited_clin_db__withCoLabsSubjectID.csv --environment production
Traceback (most recent call last):
	22: from /home/dan/.rbenv/versions/2.7.6/bin/etna:23:in `<main>'
	21: from /home/dan/.rbenv/versions/2.7.6/bin/etna:23:in `load'
	20: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/bin/etna:29:in `<top (required)>'
	19: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/application.rb:190:in `run_command'
	18: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/commands.rb:417:in `execute'
	17: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/clients/magma/workflows/update_attributes_from_csv_workflow.rb:40:in `update_attributes'
	16: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/clients/magma/workflows/crud_workflow.rb:96:in `update_records'
	15: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/clients/magma/workflows/crud_workflow.rb:96:in `each_slice'
	14: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/clients/magma/workflows/crud_workflow.rb:96:in `each'
	13: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/clients/magma/workflows/crud_workflow.rb:98:in `block in update_records'
	12: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/clients/magma/client.rb:89:in `update_json'
	11: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/client.rb:62:in `post'
	10: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/client.rb:123:in `body_request'
	 9: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/client.rb:176:in `request'
	 8: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/2.7.0/net/http.rb:606:in `start'
	 7: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/2.7.0/net/http.rb:933:in `start'
	 6: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/client.rb:177:in `block in request'
	 5: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/2.7.0/net/http.rb:1492:in `request'
	 4: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/2.7.0/net/http.rb:1536:in `transport_request'
	 3: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/2.7.0/net/http/response.rb:167:in `reading_body'
	 2: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/2.7.0/net/http.rb:1537:in `block in transport_request'
	 1: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/client.rb:178:in `block (2 levels) in request'
/home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/client.rb:158:in `status_check!': ["PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type boolean: \\"NA\\"\\nLINE 1: ... 48, -1.34, 8.94, 2.68, -1.91, 2.81, 0, 0.0, 0.0, 'NA', 'NA'...\\n                                                             ^\\n"] (Etna::Error)
```

Relevant Data Excerpt:
```
"weight","weight_z_score","weight_centile","head_circumference","head_circumference_z_score","head_circumference_centile","micro_ceph_10th","micro_ceph_3rd","sga_10th","sga_3rd"
2.68,-1.91,2.81,NA,NA,NA,NA,NA,TRUE,FALSE
```

Types:
"head_circumference" is integer type.
"head_circumference_z_score" and "head_circumference_centile" are float type
"micro_ceph_10th", "micro_ceph_3rd", "sga_10th", and "sga_3rd" are boolean type

**Comment by dtm2451** [comment]
What I would prefer to happen for NA fields would be that those attributes are left empty for the given record.  And not just for boolean attributes, but for the numeric attributes as well.

**Comment by coleshaw** [comment]
Hm, so I believe the NAs behave as expected ... NA is not a valid boolean value :smile: 

If you have cells that you want to leave blank, you can use the `--hole-value` flag in the gem. The default is `_` so you could also replace all the `NA` with `_` in your CSV.

**Comment by coleshaw** [comment]
Would probably be something like

```
$ etna administrate models attributes update_from_csv xneo1 diagnostics CoProject_limited_clin_db__withCoLabsSubjectID.csv --environment production --hole-value NA
```

**Comment by dtm2451** [comment]
worked!!!
