### ISSUE TITLE
Vulcan cancelling status when CWL changes

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#371]
So not sure how serious this is in the big picture, but I'm seeing an issue with Vulcan polling when the CWL changes. I changed a cell name and restarted Vulcan. However, the UI keeps polling and gets a 500 back from the status endpoint:

```
WARN:2021-05-07T14:00:43+00:00 User developer@ucsf.edu calling sessions#status with params {:project_name=>"xcrs1", :workflow_name=>"umap.cwl", :key=>"", :inputs=>"{:\"1_Cell_Filtering__max_nCounts\"=>30000, :\"1_Cell_Filtering__max_per_mito\"=>20, :\"1_Cell_Filtering__max_per_ribo\"=>100, :\"1_Cell_Filtering__min_nCounts\"=>200, :\"1_Cell_Filtering__min_nFeatures\"=>100, :\"2_Regress_by__regress_counts\"=>true, :\"2_Regress_by__regress_genes\"=>false, :\"2_Regress_by__regress_pct_mito\"=>true, :\"2_Regress_by__regress_pct_ribo\"=>false, :\"2_Regress_by__regress_tube_id\"=>false, :\"3_For_UMAP_and_Clustering__max_pc\"=>15, :\"3_For_UMAP_and_Clustering__n_neighbors\"=>10, :\"4_UMAP_... :\"5_Cluster_Calculation__leiden_resolution\"=>1, :\"5_Cluster_Calculation__leiden_use_weights\"=>true}"}
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 Caught unspecified error
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 Step Select_Records__selectOnFeatures has no backing definition.
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 /app/lib/orchestration.rb:316:in `build_target_for'
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 /app/lib/orchestration.rb:309:in `block in build_target_for'
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 /app/lib/orchestration.rb:307:in `each'
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 /app/lib/orchestration.rb:307:in `build_target_for'
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 /app/lib/server/controllers/sessions_controller.rb:59:in `step_status_json'
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 /app/lib/server/controllers/sessions_controller.rb:51:in `block (2 levels) in all_steps_status'
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 /app/lib/server/controllers/sessions_controller.rb:48:in `map'
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 /app/lib/server/controllers/sessions_controller.rb:48:in `block in all_steps_status'
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 /app/lib/server/controllers/sessions_controller.rb:47:in `map'
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 /app/lib/server/controllers/sessions_controller.rb:47:in `all_steps_status'
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 /app/lib/server/controllers/sessions_controller.rb:41:in `status_payload'
vulcan_app_1      | ERROR:2021-05-07T14:00:43+00:00 7gp05 /app/lib/server/controllers/sessions_controller.rb:35:in `status'
```

I tried clearing out my local storage then reloading the page, restarting the service, restarting all containers, etc., but whenever I navigated back to the UMAP workflow, it automatically starts polling again. Perhaps there should be some max retry limit on a 500? 

It seems like when you get a 500 from some initial submit or status check, the key gets set to empty string `""`, and thus stuck in some weird state? Anyways, still trying to figure out how to stop the behavior, but seems like that editing a workflow definition when someone has a stored session leads to weird behavior?

**Comment by coleshaw** [comment]
Bah, I messed up while editing the CWL -- didn't change the downstream dependencies, too. Oops!
