### ISSUE TITLE
SC workflow: regress on tube name throws exception

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#406]
If you run the workflow with "regress by tube ids" checked, it seems to throw an exception in the "regress_and_pca.py" cell:

```
Python error while executing script: Traceback (most recent call last):
  File "/archimedes-exec/tmpb3hnmk8m/script.py", line 24, in <module>
    sc.pp.regress_out(scdata, regress_on)
  File "/root/.cache/pypoetry/virtualenvs/archimedes-9TtSrW0h-py3.8/lib/python3.8/site-packages/scanpy/preprocessing/_simple.py", line 640, in regress_out
    res = list(map(_regress_out_chunk, tasks))
  File "/root/.cache/pypoetry/virtualenvs/archimedes-9TtSrW0h-py3.8/lib/python3.8/site-packages/scanpy/preprocessing/_simple.py", line 673, in _regress_out_chunk
    result = sm.GLM(data_chunk[:, col_index], regres, family=sm.families.Gaussian()).fit()
  File "/root/.cache/pypoetry/virtualenvs/archimedes-9TtSrW0h-py3.8/lib/python3.8/site-packages/statsmodels/genmod/generalized_linear_model.py", line 311, in __init__
    super(GLM, self).__init__(endog, exog, missing=missing,
  File "/root/.cache/pypoetry/virtualenvs/archimedes-9TtSrW0h-py3.8/lib/python3.8/site-packages/statsmodels/base/model.py", line 237, in __init__
    super(LikelihoodModel, self).__init__(endog, exog, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/archimedes-9TtSrW0h-py3.8/lib/python3.8/site-packages/statsmodels/base/model.py", line 77, in __init__
    self.data = self._handle_data(endog, exog, missing, hasconst,
  File "/root/.cache/pypoetry/virtualenvs/archimedes-9TtSrW0h-py3.8/lib/python3.8/site-packages/statsmodels/base/model.py", line 101, in _handle_data
    data = handle_data(endog, exog, missing, hasconst, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/archimedes-9TtSrW0h-py3.8/lib/python3.8/site-packages/statsmodels/base/data.py", line 672, in handle_data
    return klass(endog, exog=exog, missing=missing, hasconst=hasconst,
  File "/root/.cache/pypoetry/virtualenvs/archimedes-9TtSrW0h-py3.8/lib/python3.8/site-packages/statsmodels/base/data.py", line 83, in __init__
    self.endog, self.exog = self._convert_endog_exog(endog, exog)
  File "/root/.cache/pypoetry/virtualenvs/archimedes-9TtSrW0h-py3.8/lib/python3.8/site-packages/statsmodels/base/data.py", line 508, in _convert_endog_exog
    raise ValueError("Pandas data cast to numpy dtype of object. "
ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
```

**Comment by dtm2451** [comment]
Finally removed this within #529
