### ISSUE TITLE
has_user_constraint? throws exception when auth does not have a user associated with it

### ISSUE THREAD

**Issue by corps** [mountetna/monoetna#731]
https://github.com/mountetna/monoetna/blame/master/etna/lib/etna/route.rb#L158
https://rollbar.com/ucsf/Metis/items/108/?person_page=0&#traceback

I think this can effect any etna app with public routes.

From metis logs, for instance: 

```
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: WARN:2022-01-25T01:03:30+00:00 iv7wr0 User unknown calling upload#upload with params {:file_size=>"", :action=>"blob", :metis_uid=>"2b7418b5-65a6-4f88-8121-85d19acc7a07", :blob_data=>"{:filename=>\"local.path\", :type=>\"application/octet-stream\", :name=>\"blob_data\", :tempfile=>#<Tempfile:/tmp/RackMultipart20220125-1-1fviqa0.path>, :head=>\"Content-Disposition: form-data; name=\\\"blob_data\\\"; filename=\\\"local.path\\\"\\r\\nContent-Length: 4194304\\r\\nContent-Type: application/octet-stream\\r\\nContent-Transfer-Encoding: binary\\r\\n\"}", :upload_path=>"/triage/upload/waiting_room/fastq.ucsf.edu/SSD/220120_A00351_0646_BH227JDRX2_RNA/BDAC12/DSCOLAB_AIP1_POOL_PILOT_KA_SCG1_S1_L001_R1_001.fastq.gz?X-Etna-Signature=e7860d198bfcf3caf111e0aebeacb40b45ce8b0de5966fdc3a5c491ba385b83f&X-Etna-Expiration=2022-01-26T00%3A55%3A17%2B00%3A00&X-Etna-Nonce=3458f324ff53795f3b1a9f7381fb543e&X-Etna-Id=metis&X-Etna-Headers=email%2Cname&X-Etna-Email=etna.agent%40ucsf.edu&X-Etna-Name=Polyphemus+User", :next_blob_size=>"4194304", :next_blob_hash=>"7e520ec3d3c9b6d004510e8544b57f77", :current_byte_position=>"3560965120", :"X-Etna-Signature"=>"e7860d198bfcf3caf111e0aebeacb40b45ce8b0de5966fdc3a5c491ba385b83f", :"X-Etna-Expiration"=>"2022-01-26T00:55:17+00:00", :"X-Etna-Nonce"=>"3458f324ff53795f3b1a9f7381fb543e", :"X-Etna-Id"=>"metis", :"X-Etna-Headers"=>"email,name", :"X-Etna-Email"=>"etna.agent@ucsf.edu", :"X-Etna-Name"=>"Polyphemus User", :email=>"etna.agent@ucsf.edu", :name=>"Polyphemus User", :project_name=>"triage", :bucket_name=>"waiting_room", :file_path=>"fastq.ucsf.edu/SSD/220120_A00351_0646_BH227JDRX2_RNA/BDAC12/DSCOLAB_AIP1_POOL_PILOT_KA_SCG1_S1_L001_R1_001.fastq.gz"}
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 undefined method `[]' for nil:NilClass
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /etna/lib/etna/route.rb:158:in `has_user_constraint?'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /etna/lib/etna/auth.rb:131:in `update_payload'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /etna/lib/etna/auth.rb:146:in `approve_user'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /etna/lib/etna/auth.rb:18:in `call'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /etna/lib/etna/symbolize_params.rb:10:in `call'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /etna/lib/etna/parse_body.rb:38:in `call'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /etna/lib/etna/metrics.rb:22:in `call'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /etna/lib/etna/cross_origin.rb:34:in `actual_response'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /etna/lib/etna/cross_origin.rb:11:in `call'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /app/vendor/bundle/2.5.9/ruby/2.5.0/gems/puma-5.5.2/lib/puma/configuration.rb:249:in `call'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /app/vendor/bundle/2.5.9/ruby/2.5.0/gems/puma-5.5.2/lib/puma/request.rb:77:in `block in handle_request'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /app/vendor/bundle/2.5.9/ruby/2.5.0/gems/puma-5.5.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /app/vendor/bundle/2.5.9/ruby/2.5.0/gems/puma-5.5.2/lib/puma/request.rb:76:in `handle_request'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /app/vendor/bundle/2.5.9/ruby/2.5.0/gems/puma-5.5.2/lib/puma/server.rb:447:in `process_client'
Jan 24 17:03:30 metis.ucsf.edu metis_app[16538]: ERROR:2022-01-25T01:03:30+00:00 /app/vendor/bundle/2.5.9/ruby/2.5.0/gems/puma-5.5.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by coleshaw** [comment]
Huh, interesting. Thanks for finding this! I didn't realize that upload could be anonymous...?
