### ISSUE TITLE
Etna gem: Using Ruby 2.7 to create projects throws exception

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#919]
Using the command `$ etna administrate project create` works fine when using  Ruby 2.5.7 and `etna` version `0.1.44`. However, if you upgrade your local environment to Ruby 2.7.6 to match our containers, the same command throws an exception:

```
$ ruby --version
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
$ etna administrate project create test_proj2 "Test Project2" --environment development
Creating Janus project.
Done! Adding you as an administrator on the project.
Done with setting up the project in Janus!
Creating the project in Magma.
Done! Adding your new project record.
Traceback (most recent call last):
	12: from /home/e/.rbenv/versions/2.7.6/bin/etna:23:in `<main>'
	11: from /home/e/.rbenv/versions/2.7.6/bin/etna:23:in `load'
	10: from /home/e/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.44/bin/etna:18:in `<top (required)>'
	 9: from /home/e/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.44/lib/etna/application.rb:211:in `run_command'
	 8: from /home/e/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.44/lib/commands.rb:140:in `execute'
	 7: from /home/e/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.44/lib/etna/clients/magma/workflows/create_project_workflow.rb:89:in `create!'
	 6: from /home/e/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.44/lib/etna/clients/magma/workflows/create_project_workflow.rb:84:in `setup_magma_project!'
	 5: from /home/e/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.44/lib/etna/clients/magma/workflows/create_project_workflow.rb:62:in `create_magma_project_record!'
	 4: from /home/e/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.44/lib/etna/clients/magma/client.rb:80:in `update'
	 3: from /home/e/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.44/lib/etna/client.rb:56:in `multipart_post'
	 2: from /home/e/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.44/lib/etna/client.rb:56:in `new'
	 1: from /home/e/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/multipart-post-2.2.3/lib/multipart/post/multipartable.rb:50:in `initialize'
/home/e/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/multipart-post-2.2.3/lib/multipart/post/multipartable.rb:74:in `symbolize_keys': undefined method `transform_keys' for #<Array:0x000055abd631fe98> (NoMethodError)
Did you mean?  transpose
```

Seems like somewhere in the workflow or update JSON, one of the hashes is getting incorrectly (?) converted to an Array? Unclear if it's an issue with the `multipart-post` library or our workflow...

**Comment by coleshaw** [comment]
For me, 2.5.7 worked, though seems like not for @dtm2451 ?

```
$ ruby --version
ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux]
$ etna administrate project create test_proj "Test Project" --environment development
Creating Janus project.
Done! Adding you as an administrator on the project.
Done with setting up the project in Janus!
Creating the project in Magma.
Done! Adding your new project record.
Add more users? Y/n
n
All complete!
You need to visit Janus to refresh your token.
You can now log into any app to manage your data.
```

**Comment by coleshaw** [comment]
This is very mysterious...
