### ISSUE TITLE
Metis: mkdir_p throws exception when folder path exists

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#955]
Currently, Metis API for `mkdir_p` throws an exception when the folder path exists:

```
ERROR:2022-07-19T13:44:20+00:00 PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "folders_bucket_id_folder_id_folder_name_key"

DETAIL:  Key (bucket_id, folder_id, folder_name)=(122, 212669, 201013_A00269_0415_BHGLHLDSXY_NST10_CD8_GEX_fastqs) already exists.

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:154:in `exec'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:154:in `block in execute_query'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:154:in `execute_query'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel_pg-1.15.0/lib/sequel/extensions/pg_streaming.rb:92:in `execute_query'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:142:in `block in execute'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:119:in `check_disconnect_errors'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:142:in `execute'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:498:in `_execute'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel_pg-1.15.0/lib/sequel/extensions/pg_streaming.rb:47:in `_execute'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:316:in `block (2 levels) in execute'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:519:in `check_database_errors'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:316:in `block in execute'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/database/connecting.rb:269:in `synchronize'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:316:in `execute'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/dataset/actions.rb:1093:in `execute'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/postgres.rb:610:in `fetch_rows'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel_pg-1.15.0/lib/sequel/extensions/pg_streaming.rb:122:in `fetch_rows'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/dataset/actions.rb:946:in `with_sql_each'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/dataset/actions.rb:954:in `with_sql_first'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/adapters/shared/postgres.rb:1723:in `insert_select'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1735:in `_insert_select_raw'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1708:in `_insert'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1780:in `block (2 levels) in _save'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1036:in `around_create'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1777:in `block in _save'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1036:in `around_save'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1772:in `_save'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1486:in `block (2 levels) in save'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1938:in `block in checked_transaction'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/database/transactions.rb:258:in `_transaction'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/database/transactions.rb:233:in `block in transaction'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/database/connecting.rb:269:in `synchronize'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/database/transactions.rb:195:in `transaction'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1938:in `checked_transaction'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1486:in `block in save'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1926:in `checked_save_failure'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:1486:in `save'

ERROR:2022-07-19T13:44:20+00:00 /bundle/ruby/2.7.0/gems/sequel-5.57.0/lib/sequel/model/base.rb:254:in `create'

ERROR:2022-07-19T13:44:20+00:00 /app/lib/models/folder.rb:26:in `block in mkdir_p'

ERROR:2022-07-19T13:44:20+00:00 /app/lib/models/folder.rb:16:in `each'

ERROR:2022-07-19T13:44:20+00:00 /app/lib/models/folder.rb:16:in `inject'

ERROR:2022-07-19T13:44:20+00:00 /app/lib/models/folder.rb:16:in `mkdir_p'
```

Might be nice to just swallow any "folder exists" errors, like the Linux version, so can call the endpoint idempotently...

```
       -p, --parents
              no error if existing, make parent directories as needed
```

**Comment by coleshaw** [comment]
Oh, haha, the source code indicates that this should already be happening, so perhaps just need to catch a different exception?
