### ISSUE TITLE
Airflow: Large file (>25 GB) transfers to Metis die near the end?

### ISSUE THREAD

**Issue by coleshaw** [mountetna/monoetna#971]
I've had this a couple of times, hard to replicate, but some large file transfers using the CAT -> Metis ETL in Airflow seem to die at (or very near) the end of the transfer (estimating based on time). Get a stacktrace like:

```
[2022-07-29, 10:28:44 PDT] {standard_task_runner.py:89} ERROR - Failed to execute job 116810 for task xneo2_files.ingest__1
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/mountetna/metis.py", line 494, in upload_parts
    self.upload_blob(
  File "/home/airflow/.local/lib/python3.8/site-packages/mountetna/metis.py", line 438, in upload_blob
    response = self.session.post(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 652, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/mountetna/etna_base.py", line 38, in assert_status
    raise HTTPError(error_message, response=response)
requests.exceptions.HTTPError: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/etna/etls/cat.py", line 162, in ingest
    self.handle_metis_ingest(
  File "/home/airflow/.local/lib/python3.8/site-packages/etna/etls/remote_helpers_base.py", line 123, in handle_metis_ingest
    for blob in metis.upload_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/mountetna/metis.py", line 514, in upload_parts
    yield from self.upload_parts(
  File "/home/airflow/.local/lib/python3.8/site-packages/mountetna/metis.py", line 490, in upload_parts
    blob_data = upload.read_next_blob()
  File "/home/airflow/.local/lib/python3.8/site-packages/mountetna/metis.py", line 287, in read_next_blob
    raise ValueError(
ValueError: Upload source stream requires restart, upload has failed.
```

No corresponding errors in Metis logs that I can see (other uploads appear to be fine), wondering if there is something getting messed up at the last chunk?

**Comment by corps** [comment]
One other way to improve upload performance, but gets a bit more tricky, is better resuming behavior.  The trick is, the metis uuid allows resuming an upload already, BUT the client needs to ensure that it only resumes an upload when the hash of the file has not changed.  I think the simple fix here is for the metis_uuid used by the client to be consistent _per file upload hash_ to ensure that the 'session' of uploading a file is consistent with the hash contents of the file.

**Comment by coleshaw** [comment]
Ooooh, that would be neat!

How would that work for the streaming uploads? I thought with pipes, those aren't necessarily seekable, so the source wouldn't be able to resume the upload from the last byte position, without consuming everything again?

**Comment by corps** [comment]
Worst case, you can still restart the source stream from CAT and discard bytes until you find the right position.

This would be 'faster' then restarting the whole upload since I imagine the upload into Metis is the bottle neck more than the streaming down from CAT?

**Comment by coleshaw** [comment]
Ah yeah, that makes sense! At the very least, better than reuploading the bits, too.
