### ISSUE TITLE
better retry / wait mechanisms for the etna gem

### ISSUE THREAD

**Issue by dtm2451** [mountetna/monoetna#986]
In running `etna administrate models apply_template coprojects_template --environment production --file coprojects_template_models_project_tree.csv` today, I saw:

```
File coprojects_template_models_project_tree.csv is well formatted.  Calculating expected changes...

sc_seq changes:
 * add_link: 1

sc_seq_pool changes:
 * add_link: 1

Would you like to execute?
Confirm Y/n:
Y
Executing add_link on ["sc_seq", "sc_seq"]...
Executing add_link on ["sc_seq_pool", "sc_seq_pool"]...
Traceback (most recent call last):
	21: from /home/dan/.rbenv/versions/2.7.6/bin/etna:23:in `<main>'
	20: from /home/dan/.rbenv/versions/2.7.6/bin/etna:23:in `load'
	19: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/bin/etna:29:in `<top (required)>'
	18: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/application.rb:190:in `run_command'
	17: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/commands.rb:345:in `execute'
	16: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/clients/magma/workflows/model_synchronization_workflow.rb:32:in `execute_planned!'
	15: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/clients/magma/workflows/model_synchronization_workflow.rb:32:in `each'
	14: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/clients/magma/workflows/model_synchronization_workflow.rb:33:in `block in execute_planned!'
	13: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/clients/magma/workflows/model_synchronization_workflow.rb:42:in `execute_update'
	12: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/clients/magma/client.rb:98:in `update_model'
	11: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/client.rb:62:in `post'
	10: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/client.rb:123:in `body_request'
	 9: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/client.rb:176:in `request'
	 8: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/2.7.0/net/http.rb:606:in `start'
	 7: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/2.7.0/net/http.rb:933:in `start'
	 6: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/client.rb:177:in `block in request'
	 5: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/2.7.0/net/http.rb:1492:in `request'
	 4: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/2.7.0/net/http.rb:1536:in `transport_request'
	 3: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/2.7.0/net/http/response.rb:167:in `reading_body'
	 2: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/2.7.0/net/http.rb:1537:in `block in transport_request'
	 1: from /home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/client.rb:178:in `block (2 levels) in request'
/home/dan/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/etna-0.1.46/lib/etna/client.rb:158:in `status_check!': <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> (Etna::Error)
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid\r
response from an upstream server.<br />\r
The proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>
```

Which likely means the gem doesn't properly wait for the magma restart that would have been involved in applying these updates.

Luckily, with a second run, it completed just fine:

```
dan@pop-os:~$ etna administrate models apply_template coprojects_template --environment production --file coprojects_template_models_project_tree.csv 
File coprojects_template_models_project_tree.csv is well formatted.  Calculating expected changes...

sc_seq_pool changes:
 * add_link: 1

Would you like to execute?
Confirm Y/n:
Y
Executing add_link on ["sc_seq_pool", "sc_seq_pool"]...
dan@pop-os:~$
```

**Comment by corps** [comment]
Yup, this is kind of a known issue.  Retrying a few times usually is required to fully complete the changes due to the requirement of restart.

I suppose the simple solution is for the client to catch the gateway and delay and retry.
